### PR TITLE
fix: Request Feedback Not Recorded

### LINKED ISSUE #289: Request Feedback not recorded
**Describe the bug**
It seems that currenly only `Responses` are recorded in `ParameterFeedback` (in `process_response`, line 211 -> line 109 in `executor.rs`). The `Request`s are not recorded in it however, leading to failures when trying to resolve `IReference`s. 

**Versions:**
 - Wuppiefuzz: 4745e0b

**To Reproduce**

I've output a corpus entry like this:

```
- method: POST
  path: /_matrix/client/v3/login
  body: !ApplicationJson
    identifier:
      type: !String m.id.user
      user: !String WuppieFuzz
    password: !String WuppieFuzz
    type: !String m.login.password
- method: POST
  path: /_matrix/client/v3/register
  body: !ApplicationJson
    password: !ReferenceToEarlierRequest
      request: 0
      parameter_access: !Request
        Body:
        - !Name password
    username: !String cheeky_monkey
```
When using this to fuzz (against a suitable API...) I get the following error:

```
ERROR wuppiefuzz::reproducer] Cannot instantiate request: missing value for backreferenced parameter: Unknown error: invalid request-backreference to 0:password
```

**Expected behavior**
The request reference should be resolved. This should be easily achieved by recording `Request`s in the `ParameterFeedback` as well as the `Response`s.

### PR DESCRIPTION
**Pull request by Jelle-Nauta**
Closes #289

### CODE REVIEW

File: src/parameter_feedback.rs [hunk 1]
```diff
@@ -120,6 +120,40 @@ impl ParameterFeedback {
...
+            Body::Empty => {}
+            Body::TextPlain(body)
+            | Body::ApplicationJson(body)
+            | Body::XWwwFormUrlencoded(body) => self.add_request_parameter(
+                ParameterAddressing::new(
+                    request_index,
+                    ParameterAccess::request_body(ParameterAccessElements::new()),
+                ),
+                body.clone(),
+            ),
```
Comment (grebnetiew) [inline src/parameter_feedback.rs:139]: Not entirely sure how this works - it seems it will add only the entire body contents with an empty parameter access instead of adding e.g. the fields of the object in the body with their (sub)field names as the parameter access elements? I thought that's what we had the whole Vec-based access thing for

File: src/parameter_feedback.rs [hunk 2]
```diff
@@ -156,3 +190,158 @@ impl ParameterFeedback {
...
+            feedback
+                .get(
+                    0,
+                    &ParameterAccess::request_body(ParameterAccessElements::from_elements(&[
+                        ParameterAccessElement::Name("outer".to_string()),
+                        ParameterAccessElement::Name("inner".to_string()),
+                    ])),
+                )
+                .map(ParameterContents::to_value),
+            Some(serde_json::json!(37))
```
Comment (grebnetiew) [inline src/parameter_feedback.rs:277]: Well, it sure seems to work :)

**Review by grebnetiew — APPROVED** [review]
Very cool to have tests for this, thanks :)
